// <auto-generated />
using System;
using AdministrativoEscolar.CORE.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdministrativoEscolar.CORE.Migrations
{
    [DbContext(typeof(AdmEscolarDbContext))]
    partial class AdmEscolarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAluno"));

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDelecao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MatriculaIdMatricula")
                        .HasColumnType("int");

                    b.Property<string>("NmAluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuCPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuRG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SbnmAluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxNacionalidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAluno");

                    b.HasIndex("MatriculaIdMatricula");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.AlunoStatusLetivoHistorico", b =>
                {
                    b.Property<int>("IdStatusLetivoHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusLetivoHistorico"));

                    b.Property<int?>("AlunoIdAluno")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDelecao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlStatusAtual")
                        .HasColumnType("bit");

                    b.Property<int?>("StatusLetivoIdStatusLetivo")
                        .HasColumnType("int");

                    b.HasKey("IdStatusLetivoHistorico");

                    b.HasIndex("AlunoIdAluno");

                    b.HasIndex("StatusLetivoIdStatusLetivo");

                    b.ToTable("AlunoStatusLetivoHistoricos");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.EnderecoAluno", b =>
                {
                    b.Property<int>("IdEnderecoAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnderecoAluno"));

                    b.Property<int?>("AlunoIdAluno")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDelecao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlEnderecoAtual")
                        .HasColumnType("bit");

                    b.Property<string>("NuCepEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxBairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxCidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnderecoAluno");

                    b.HasIndex("AlunoIdAluno");

                    b.ToTable("EnderecoAlunos");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.Matricula", b =>
                {
                    b.Property<int>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatricula"));

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDelecao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NuMatricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMatricula");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.ResponsavelAluno", b =>
                {
                    b.Property<int>("IdResponsavelAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResponsavelAluno"));

                    b.Property<int?>("AlunoIdAluno")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDelecao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlResponsavelPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("NmResponsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuCPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuRG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResponsavelAluno");

                    b.HasIndex("AlunoIdAluno");

                    b.ToTable("ResponsavelAlunos");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.StatusLetivo", b =>
                {
                    b.Property<int>("IdStatusLetivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusLetivo"));

                    b.Property<string>("CdStatusLetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxStatusLetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxTipoEnsino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatusLetivo");

                    b.ToTable("StatusLetivos");

                    b.HasData(
                        new
                        {
                            IdStatusLetivo = 1,
                            CdStatusLetivo = "primeiro_creche",
                            TxStatusLetivo = "1º Creche",
                            TxTipoEnsino = "creche"
                        },
                        new
                        {
                            IdStatusLetivo = 2,
                            CdStatusLetivo = "segundo_creche",
                            TxStatusLetivo = "2º Creche",
                            TxTipoEnsino = "creche"
                        },
                        new
                        {
                            IdStatusLetivo = 3,
                            CdStatusLetivo = "terceiro_creche",
                            TxStatusLetivo = "3º Creche",
                            TxTipoEnsino = "creche"
                        },
                        new
                        {
                            IdStatusLetivo = 4,
                            CdStatusLetivo = "primeiro_ensino_infantil",
                            TxStatusLetivo = "1º Ensino Infantil",
                            TxTipoEnsino = "ensino_infantil"
                        },
                        new
                        {
                            IdStatusLetivo = 5,
                            CdStatusLetivo = "segundo_ensino_infantil",
                            TxStatusLetivo = "2º Ensino Infantil",
                            TxTipoEnsino = "ensino_infantil"
                        },
                        new
                        {
                            IdStatusLetivo = 6,
                            CdStatusLetivo = "primeiro_fundamental",
                            TxStatusLetivo = "1º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_um"
                        },
                        new
                        {
                            IdStatusLetivo = 7,
                            CdStatusLetivo = "segundo_fundamental",
                            TxStatusLetivo = "2º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_um"
                        },
                        new
                        {
                            IdStatusLetivo = 8,
                            CdStatusLetivo = "terceiro_fundamental",
                            TxStatusLetivo = "3º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_um"
                        },
                        new
                        {
                            IdStatusLetivo = 9,
                            CdStatusLetivo = "quarto_fundamental",
                            TxStatusLetivo = "4º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_um"
                        },
                        new
                        {
                            IdStatusLetivo = 10,
                            CdStatusLetivo = "quinto_fundamental",
                            TxStatusLetivo = "5º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_um"
                        },
                        new
                        {
                            IdStatusLetivo = 11,
                            CdStatusLetivo = "sexto_fundamental",
                            TxStatusLetivo = "6º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_dois"
                        },
                        new
                        {
                            IdStatusLetivo = 12,
                            CdStatusLetivo = "setimo_fundamental",
                            TxStatusLetivo = "7º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_dois"
                        },
                        new
                        {
                            IdStatusLetivo = 13,
                            CdStatusLetivo = "oitavo_fundamental",
                            TxStatusLetivo = "8º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_dois"
                        },
                        new
                        {
                            IdStatusLetivo = 14,
                            CdStatusLetivo = "nono_fundamental",
                            TxStatusLetivo = "9º Fundamental",
                            TxTipoEnsino = "ensino_fundamental_dois"
                        },
                        new
                        {
                            IdStatusLetivo = 15,
                            CdStatusLetivo = "primeiro_ensino_medio",
                            TxStatusLetivo = "1º Ensino Médio",
                            TxTipoEnsino = "ensino_medio"
                        },
                        new
                        {
                            IdStatusLetivo = 16,
                            CdStatusLetivo = "segundo_ensino_medio",
                            TxStatusLetivo = "2º Ensino Médio",
                            TxTipoEnsino = "ensino_medio"
                        },
                        new
                        {
                            IdStatusLetivo = 17,
                            CdStatusLetivo = "terceiro_ensino_medio",
                            TxStatusLetivo = "3º Ensino Médio",
                            TxTipoEnsino = "ensino_medio"
                        },
                        new
                        {
                            IdStatusLetivo = 18,
                            CdStatusLetivo = "quarto_ensino_medio",
                            TxStatusLetivo = "4º Ensino Médio",
                            TxTipoEnsino = "ensino_medio"
                        },
                        new
                        {
                            IdStatusLetivo = 19,
                            CdStatusLetivo = "primeiro_ensino_medio_tecnico",
                            TxStatusLetivo = "1º Ensino Médio Técnico",
                            TxTipoEnsino = "ensino_medio_tecnico"
                        },
                        new
                        {
                            IdStatusLetivo = 20,
                            CdStatusLetivo = "segundo_ensino_medio_tecnico",
                            TxStatusLetivo = "2º Ensino Médio Técnico",
                            TxTipoEnsino = "ensino_medio_tecnico"
                        },
                        new
                        {
                            IdStatusLetivo = 21,
                            CdStatusLetivo = "terceiro_ensino_medio_tecnico",
                            TxStatusLetivo = "3º Ensino Médio Técnico",
                            TxTipoEnsino = "ensino_medio_tecnico"
                        },
                        new
                        {
                            IdStatusLetivo = 22,
                            CdStatusLetivo = "quarto_ensino_medio_tecnico",
                            TxStatusLetivo = "4º Ensino Médio Técnico",
                            TxTipoEnsino = "ensino_medio_tecnico"
                        },
                        new
                        {
                            IdStatusLetivo = 23,
                            CdStatusLetivo = "primeiro_semestre_ensino_tecnico",
                            TxStatusLetivo = "1º Semestre Ensino Técnico",
                            TxTipoEnsino = "ensino_tecnico"
                        },
                        new
                        {
                            IdStatusLetivo = 24,
                            CdStatusLetivo = "segundo_semestre_ensino_tecnico",
                            TxStatusLetivo = "2º Semestre Ensino Técnico",
                            TxTipoEnsino = "ensino_tecnico"
                        },
                        new
                        {
                            IdStatusLetivo = 25,
                            CdStatusLetivo = "terceiro_semestre_ensino_tecnico",
                            TxStatusLetivo = "3º Semestre Ensino Técnico",
                            TxTipoEnsino = "ensino_tecnico"
                        },
                        new
                        {
                            IdStatusLetivo = 26,
                            CdStatusLetivo = "quarto_semestre_ensino_tecnico",
                            TxStatusLetivo = "4º Semestre Ensino Técnico",
                            TxTipoEnsino = "ensino_tecnico"
                        },
                        new
                        {
                            IdStatusLetivo = 27,
                            CdStatusLetivo = "primeiro_semestre_superior",
                            TxStatusLetivo = "1º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 28,
                            CdStatusLetivo = "segundo_semestre_superior",
                            TxStatusLetivo = "2º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 29,
                            CdStatusLetivo = "terceiro_semestre_superior",
                            TxStatusLetivo = "3º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 30,
                            CdStatusLetivo = "quarto_semestre_superior",
                            TxStatusLetivo = "4º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 31,
                            CdStatusLetivo = "quinto_semestre_superior",
                            TxStatusLetivo = "5º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 32,
                            CdStatusLetivo = "sexto_semestre_superior",
                            TxStatusLetivo = "6º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 33,
                            CdStatusLetivo = "setimo_semestre_superior",
                            TxStatusLetivo = "7º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 34,
                            CdStatusLetivo = "oitavo_semestre_superior",
                            TxStatusLetivo = "8º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 35,
                            CdStatusLetivo = "nono_semestre_superior",
                            TxStatusLetivo = "9º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 36,
                            CdStatusLetivo = "decimo_semestre_superior",
                            TxStatusLetivo = "10º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 37,
                            CdStatusLetivo = "decimo_primeiro_semestre_superior",
                            TxStatusLetivo = "11º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        },
                        new
                        {
                            IdStatusLetivo = 38,
                            CdStatusLetivo = "decimo_segundo_semestre_superior",
                            TxStatusLetivo = "12º Semestre Superior",
                            TxTipoEnsino = "ensino_superior"
                        });
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.StatusMatricula", b =>
                {
                    b.Property<int>("IdStatusMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusMatricula"));

                    b.Property<string>("CdStatusMatricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxStatusMatricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatusMatricula");

                    b.ToTable("StatusMatriculas");

                    b.HasData(
                        new
                        {
                            IdStatusMatricula = 1,
                            CdStatusMatricula = "matriculado",
                            TxStatusMatricula = "Matriculado"
                        },
                        new
                        {
                            IdStatusMatricula = 2,
                            CdStatusMatricula = "pendente",
                            TxStatusMatricula = "Pendente"
                        },
                        new
                        {
                            IdStatusMatricula = 3,
                            CdStatusMatricula = "trancado",
                            TxStatusMatricula = "Trancado"
                        },
                        new
                        {
                            IdStatusMatricula = 4,
                            CdStatusMatricula = "cancelado",
                            TxStatusMatricula = "Cancelado"
                        },
                        new
                        {
                            IdStatusMatricula = 5,
                            CdStatusMatricula = "desistencia",
                            TxStatusMatricula = "Desistência"
                        },
                        new
                        {
                            IdStatusMatricula = 6,
                            CdStatusMatricula = "transferido",
                            TxStatusMatricula = "Transferido"
                        },
                        new
                        {
                            IdStatusMatricula = 7,
                            CdStatusMatricula = "rejeitado",
                            TxStatusMatricula = "Rejeitado"
                        },
                        new
                        {
                            IdStatusMatricula = 8,
                            CdStatusMatricula = "suspenso",
                            TxStatusMatricula = "Suspenso"
                        },
                        new
                        {
                            IdStatusMatricula = 9,
                            CdStatusMatricula = "expulso",
                            TxStatusMatricula = "Expulso"
                        },
                        new
                        {
                            IdStatusMatricula = 10,
                            CdStatusMatricula = "graduado",
                            TxStatusMatricula = "Graduado"
                        });
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.StatusMatriculaHistorico", b =>
                {
                    b.Property<int>("IdStatusMatriculaHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusMatriculaHistorico"));

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDelecao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlStatusAtual")
                        .HasColumnType("bit");

                    b.Property<int?>("MatriculaIdMatricula")
                        .HasColumnType("int");

                    b.Property<int?>("StatusMatriculaIdStatusMatricula")
                        .HasColumnType("int");

                    b.HasKey("IdStatusMatriculaHistorico");

                    b.HasIndex("MatriculaIdMatricula");

                    b.HasIndex("StatusMatriculaIdStatusMatricula");

                    b.ToTable("StatusMatriculaHistoricos");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.Aluno", b =>
                {
                    b.HasOne("AdministrativoEscolar.CORE.Entities.Matricula", "Matricula")
                        .WithMany()
                        .HasForeignKey("MatriculaIdMatricula");

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.AlunoStatusLetivoHistorico", b =>
                {
                    b.HasOne("AdministrativoEscolar.CORE.Entities.Aluno", "Aluno")
                        .WithMany("StatusLetivoHistorico")
                        .HasForeignKey("AlunoIdAluno");

                    b.HasOne("AdministrativoEscolar.CORE.Entities.StatusLetivo", "StatusLetivo")
                        .WithMany("Alunos")
                        .HasForeignKey("StatusLetivoIdStatusLetivo");

                    b.Navigation("Aluno");

                    b.Navigation("StatusLetivo");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.EnderecoAluno", b =>
                {
                    b.HasOne("AdministrativoEscolar.CORE.Entities.Aluno", "Aluno")
                        .WithMany("Enderecos")
                        .HasForeignKey("AlunoIdAluno");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.ResponsavelAluno", b =>
                {
                    b.HasOne("AdministrativoEscolar.CORE.Entities.Aluno", "Aluno")
                        .WithMany("Responsaveis")
                        .HasForeignKey("AlunoIdAluno");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.StatusMatriculaHistorico", b =>
                {
                    b.HasOne("AdministrativoEscolar.CORE.Entities.Matricula", "Matricula")
                        .WithMany("Historico")
                        .HasForeignKey("MatriculaIdMatricula");

                    b.HasOne("AdministrativoEscolar.CORE.Entities.StatusMatricula", "StatusMatricula")
                        .WithMany("HistoricoMatricula")
                        .HasForeignKey("StatusMatriculaIdStatusMatricula");

                    b.Navigation("Matricula");

                    b.Navigation("StatusMatricula");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.Aluno", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("Responsaveis");

                    b.Navigation("StatusLetivoHistorico");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.Matricula", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.StatusLetivo", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("AdministrativoEscolar.CORE.Entities.StatusMatricula", b =>
                {
                    b.Navigation("HistoricoMatricula");
                });
#pragma warning restore 612, 618
        }
    }
}
